<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Carbon Neutral Certificate</title>
  <link href="https://fonts.cdnfonts.com/css/prequel-demo" rel="stylesheet">
  <link href="https://fonts.cdnfonts.com/css/american-captain-2" rel="stylesheet">
  <link href="https://fonts.cdnfonts.com/css/rafttel-script-demo" rel="stylesheet">
  {{-- <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,300&display=swap" rel="stylesheet"> --}}


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
    
 <style>
        @page {
            margin: 0;
            padding: 0;
            page-break-after: avoid;
            page-break-before: avoid;
        }

        .footers {
            position: absolute;
            width: 100%;
            left: 24%;
            top: 78%;
        }
    </style>
</head>
<body style="margin:0;padding:0;box-sizing:border-box;font-family:'Fira Sans',sans-serif;background:#f0f0f0;">

<div style="width: 210mm; height: 297mm; background: #fff; margin: auto; padding: 30px; box-shadow: 0 0 10px rgba(0,0,0,0.2); position: relative;">

  <!-- Logo -->
  <div style="text-align:center; margin-bottom:20px;">
    <img src="http://localhost/local-crm-admin/staging-crm/crm-admin/storage/app/admin/setting/Carbon Neutral road trips 2-01.png" style="max-height:100px;">
  </div>

  <!-- Title -->
  <h1 style="text-align:center; font-size:36px; margin:0; font-family:'American Captain', sans-serif; letter-spacing:4px;">CARBON NEUTRAL</h1>
  <h2 style="text-align:center; font-size:22px; margin:5px 0 15px 0; font-family:'Rafttel Script DEMO', sans-serif;">Certificate</h2>

  <!-- Name Section -->
  <p style="text-align:center; font-size:14px; margin:0;">Presented to</p>
  <h3 style="text-align:center; font-size:24px; margin:5px 0 20px 0; font-family:'Prequel Demo', sans-serif;">{{$name}}</h3>

  <!-- Description -->
  <div style="font-size:13px; line-height:1.5; text-align:justify; color:#333;">
    <p>This certificate proudly acknowledges that your <b>{{$trip_name}}</b> has been made carbon neutral through our dedicated tree plantation initiative - a meaningful step toward a cleaner, greener planet.</p>
    <p>At Adventures Overland, we believe in exploring the world responsibly. That’s why we’ve taken a conscious step to offset the carbon emissions generated by your car during the trip.</p>
    <p>AO has developed a custom carbon calculator that evaluates emissions based on distance traveled, mileage, engine capacity, and fuel type. This ensures a transparent and measurable way to calculate our environmental impact.</p>
    <p>To offset your journey’s footprint, we partnered with Grow Trees to plant trees that will grow, protect, and give back to the Earth.</p>
  </div>

  <!-- Stats Row -->
  <div style="display: flex; justify-content: space-between; margin: 30px 0;">
    <div style="text-align:center; flex:1; border-right:2px solid #000;">
      <h3 style="font-size:18px; margin:5px 0;">{{$carnumber}}</h3>
      <p style="font-size:12px; margin:0;">Car Number</p>
    </div>
    <div style="text-align:center; flex:1; border-right:2px solid #000;">
      <h3 style="font-size:18px; margin:5px 0;">{{$distance}} km</h3>
      <p style="font-size:12px; margin:0;">Total Distance Covered<br>(approx)</p>
    </div>
    <div style="text-align:center; flex:1; border-right:2px solid #000;">
      <h3 style="font-size:18px; margin:5px 0;">{{$carbon_emission}} kg</h3>
      <p style="font-size:12px; margin:0;">Carbon Emissions<br>Generated and Offset</p>
    </div>
    <div style="text-align:center; flex:1;">
      <h3 style="font-size:18px; margin:5px 0;">{{$no_of_trees}}</h3>
      <p style="font-size:12px; margin:0;">Trees we planted<br>on your behalf</p>
    </div>
  </div>

  <!-- Final Paragraph -->
  <div style="font-size:13px; line-height:1.5; text-align:justify; color:#333;">
    <p>We want you to travel with purpose, knowing that every mile you cover with us leaves no carbon footprint. If you’d like to continue making a difference, visit our website to offset the carbon footprint of your future adventures too.</p>
    <p>We’re proud to share that Adventures Overland began its carbon-neutral journey in 2024. Since then, we’ve planted <b>[X number]</b> trees at <b>[X location]</b> as part of our commitment to sustainability.</p>
  </div>

  <!-- Logos -->
  <div style="text-align:center; margin:40px 0;">
    <img src="http://localhost/local-crm-admin/staging-crm/crm-admin/storage/app/admin/setting/AO Logo-F-01.png" style="width:55px; margin:0 10px;">
    <img src="http://localhost/local-crm-admin/staging-crm/crm-admin/storage/app/admin/setting/Goldenmile.png" style="width:50px; margin:0 10px;">
    <img src="http://localhost/local-crm-admin/staging-crm/crm-admin/storage/app/admin/setting/GTsociallogo.png" style="width:80px; margin:0 10px;">
    <img src="http://localhost/local-crm-admin/staging-crm/crm-admin/storage/app/admin/setting/sahyadri.png" style="width:95px; margin:0 10px;">
    <img src="http://localhost/local-crm-admin/staging-crm/crm-admin/storage/app/admin/setting/Treeties-black.png" style="width:140px; margin:0 10px;">
  </div>

  
  <!-- Signatures -->
      <div style="display:flex;justify-content:space-between;">
        <table style="width:100%;">
          <tr>
            <td style="text-align:center;">
              <img src="http://localhost/local-crm-admin/staging-crm/crm-admin/storage/app/admin/setting/Tushar Agarwal.png" alt="" style="width:70px;">
              <h6 style="font-size:15px;margin:0px;">
                <p style="font-family:'Poppins',sans-serif;font-weight:bold;margin:0px;">TUSHAR AGARWAL</p>
              </h6>
              <hr style="margin:6px 0px 12px 0px;">
              <p style="font-size:14px;font-weight:400;line-height:4px;font-family:'Poppins',sans-serif;">CO-FOUNDER ADVENTURES OVERLAND</p>
            </td>
            <td style="text-align:center;padding-left:220px;">
              <img src="http://localhost/local-crm-admin/staging-crm/crm-admin/storage/app/admin/setting/Sanjay-2.png" alt="" style="width:70px;">
              <h6 style="font-size:15px;margin:0px;">
                <p style="font-family:'Poppins',sans-serif;font-weight:bold;margin:0px;">SANJAY MADAN</p>
              </h6>
              <hr style="margin:6px 0px 12px 0px;">
              <p style="font-size:14px;font-weight:400;line-height:4px;font-family:'Poppins',sans-serif;">CO-FOUNDER ADVENTURES OVERLAND</p>
            </td>
          </tr>
        </table>
      </div>
  

  <!-- Footer Wave -->
  <div style="position:absolute; bottom:0; left:0; width:100%;">
    <img src="http://localhost/local-crm-admin/staging-crm/crm-admin/storage/app/admin/setting/bottem.svg" style="width:100%;">
  </div>
</div>
</div>
</body>
</html>